apiVersion: v1
kind: Pod
spec:
  serviceAccount: jenkins
  containers:
    - name: shell
      image: alpine
      command:
        - cat
      tty: true
    - name: python
      image: python:3.7-alpine3.14
      command:
        - cat
      tty: true
    - name: pytest
      image: qnib/pytest
      command:
        - cat
      tty: true
    - name: deploy
      image: cdrx/pyinstaller-linux:python3
      command:
        - cat
      tty: true
